### ISSUE TITLE
Viñetas

### ISSUE THREAD

**Issue by YanetGelhorn** [pdep-utn-frd/presentacion-2022-nycatino#1]
Hola! Como sugerencia, podrías revisar las viñetas, no te las tomó.

**Comment by nycatino** [comment]
Ahi lo arreglé, gracias!

**Comment by juanbono** [comment]
Hola, cuando una issue es resuelta lo mejor es cerrarla para que no ocupe espacio junto a las que aún están sin resolver. Saludos.
